{% set name = "aixd_ara" %}
{% set version = "0.10.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aixd_ara-{{ version }}.tar.gz
  sha256: 082cd6a8d6459fd79dabec26c9fc19e3a94217a7890a18bfd35e20b9e535b574

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - aixd =0.12.1
    - compas >=2,<3
    - flask
    - python >={{ python_min }}

test:
  imports:
    - aixd_ara
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gramaziokohler.github.io/aixd_ara/
  summary: 'Grasshopper plugin for data-driven and inverse design methods with generative AI.'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - funkchaser
    - gonzalocasas
