{% set name = "aixd_ara" %}
{% set version = "0.10.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aixd_ara-{{ version }}.tar.gz
  sha256: 7eff08b6c6d0157ec0bc0ab98a35c6d09278a409f663171f880b8b5ce5f47920

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - aixd =0.13.0
    - compas >=2,<3
    - flask
    - python >={{ python_min }}

test:
  imports:
    - aixd_ara
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gramaziokohler.github.io/aixd_ara/
  summary: 'Grasshopper plugin for data-driven and inverse design methods with generative AI.'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - funkchaser
    - gonzalocasas
