{% set name = "aixd_ara" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aixd_ara-{{ version }}.tar.gz
  sha256: 8e61efa1d2ae5ed614939656d51837b7cb38625acc405856595547dc2ee35015

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - aixd >=0.10.0
    - compas >=2,<3
    - flask
    - python >=3.9

test:
  imports:
    - aixd_ara
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gramaziokohler.github.io/aixd_ara/
  summary: 'Grasshopper plugin for data-driven and inverse design methods with generative AI.'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - funkchaser
    - gonzalocasas
